services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sentinel-pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sentinel_ai
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
