server:
  port: 8090

spring:
  application:
    name: sentinel-ai
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sentinel_ai?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
sentinel:
  ai:
    enabled: false
    model: qwen3.5-plus
    api-key: ${AI_DASHSCOPE_API_KEY:}
    temperature: 0.2
    max-ai-calls-per-scan: -1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.zhuangjie.sentinel: debug
